### PR TITLE
Add DFN-14-1EP_3x3mm_Pitch0.40mm to Housings

### PR DESCRIPTION
**Pull request by mifi2909**
I am working on the MAX9814 component that has a footprint that was not yet in the repo's.

The datasheet for the MAX9814 is here: [datasheet](https://datasheets.maximintegrated.com/en/ds/MAX9814.pdf). Their housing reference for this component is T1433-2.
The housing spec from Maxim is here: [housing](http://pdfserv.maximintegrated.com/package_dwgs/21-0137.PDF)
The landing patern from Maxim is here: [land pattern](http://pdfserv.maximintegrated.com/land_patterns/90-0063.PDF)

Screenshot of new footprint:
dfn-14-1ep_3x3mm_pitch0 40mm

I have not done a 3D model (yet) so I removed any reference to it.

Could you please comment on this first version, to see if it can be used to finish the MAX9814 component?
Thanks.
m

### CODE REVIEW

**Comment by mifi2909** [comment]
I noticed that in my screenshot included above, the REF** is missing from the Fab.Layer. 
It is there in the mod.

**Comment by mifi2909** [comment]
Reference to 3D model added:
${KISYS3DMOD}/Housings_DFN_QFN.3dshapes/DFN-14-1EP_3x3mm_Pitch0.40mm.wrl

The 3D model itself is being made by 'Shack'. See also: [forum message](https://forum.kicad.info/t/new-component-max9814-footprint-pin-names-etc/6557/18).

**Comment by Shackmeister** [comment]
I believe the Epad should be split into multiple squares. you should check a similar package :)
also the Epad should be pin 15

**Comment by mifi2909** [comment]
I can do that @Shackmeister and I will. I must admit, I do not fully understand why, but that's just my ignorance, no doubt  ;-)
I have not found rules in the KLC to support this. Perhaps it would be a good idea to add them?

**Comment by Shackmeister** [comment]
I believe the reason is to avoid to much solder paste when sending it to production. But not sure :)

**Comment by mifi2909** [comment]
There is an interesting issue with connections. The datasheet recommends the EP to be connected to GND, but since the component does not have a pad 15, this cannot be done in eeschema. Hence there is the need to add connections in pcbnew that do not exist in the schematic. I dislike that. The same is true for pins 4 and 11, which are NC pins according to the datasheet, but need to be connected to GND. 

It is perhaps a bit of a philosophical argument. I would rather see that all electrical connections are in eeschema, but currently it is like it is.

**Comment by Shackmeister** [comment]
You always add the Epad In Eeschema as pin 15 (or whatever the next free is)

**Comment by mifi2909** [comment]
With 'in eeschema' do you mean in the component?
I should add a 15th pad in the component as well as a NC pin?

**Comment by SchrodingersGat** [comment]
Hi @mifi2909 thanks for the contribution. A couple of small points:

a) Please change pitch naming from `0.40mm` to `0.4mm` to match convention of other footprints

Regarding splitting the end-point into multiple sections:

This is done to reduce the amount of solder paste that gets deposited on the pads via the stencil. The epad is split into multiple sections and each section has the aperture reduced, normally based upon datasheet recommendation.

However the land-pattern datasheet you have linked is very brief (too brief!) 

I would recommend reducing the solder-paste margin on each of the e-pads to -0.1mm:

screenshot from 2017-05-27 09-32-46

**Comment by mifi2909** [comment]
Ok. I will give that a go.
Hmm, that means the name of the 3D model is changing too...  oh well.
I used 0.40 to clearly show the difference from 0.45, which is also in the lib. But I will follow the convention. Standardization is good.

**Comment by SchrodingersGat** [comment]
Great work, thanks :)

**Pull request merged**
