### PR TITLE
added Kisysmod3D and added UDFN10 footprint

### PR DESCRIPTION
**Pull request by Shackmeister**
udfn10

### CODE REVIEW

**Comment by Shackmeister** [comment]
And that's about all Im gonna fix :) @SchrodingersGat or @Rene_Poschl can any of you have a look at this?

**Comment by poeschlr** [comment]
From what I see in the Screenshot I would suggest you rotate the reference on the fab layer. You should then be able to increase the font size.

**Comment by poeschlr** [comment]
Is there a reason for pad 1 being smaller in y direction?

**Comment by Shackmeister** [comment]
Ill fix both, the pin 1 was a mistake.. Ill see how many if the other will need the reference rotated

**Comment by Shackmeister** [comment]
@poeschlr I have now fixed all of the refdef's. Personally I think the 10% text thickness suggested by KLC should be revisited, its looking very thin.

**Comment by SchrodingersGat** [comment]
@Shackmeister agreed the text looks much better with 0.1mm width - please increase RefDes with to this :)

**Comment by Shackmeister** [comment]
0.1mm thickness for which width? :) I have added refdef to all packages in the repo

**Comment by SchrodingersGat** [comment]
Sorry, for the new UDFN package

**Comment by poeschlr** [comment]
This pr does not only contain the new footprint. Here a review of all the other footprints you changed:
I only reviewed the "features" you changed (Example: you changed something on the fab outline -> i checked it.)

---

DFN-10-1EP_2x3mm_Pitch0.5mm:
pin 1 marker could be a bit smaller. (25% of package size) I would accept it as is. If you are willing to change something here, maybe we could also make this in a new pull request.

Same for DFN-12-1EP_2x3mm_Pitch0.45mm, DFN-14-1EP_3x4mm_Pitch0.5mm, DFN-16-1EP_3x4mm_Pitch0.45mm, DFN-6-1EP_2x2mm_Pitch0.5mm, DFN-6-1EP_2x2mm_Pitch0.65mm, DFN-8-1EP_2x2mm_Pitch0.45mm, DFN-8-1EP_2x2mm_Pitch0.5mm, DFN-8-1EP_2x3mm_Pitch0.5mm, DFN-8-1EP_3x2mm_Pitch0.5mm, DFN-8_2x2mm_Pitch0.5mm, QFN-20-1EP_3x4mm_Pitch0.5mm, QFN-24-1EP_3x3mm_Pitch0.4mm, QFN-24-1EP_3x4mm_Pitch0.4mm, QFN-28-1EP_3x6mm_Pitch0.5mm and VDFN-8-1EP_2x2mm_Pitch0.5mm. 

For DFN-6-1.3x1.2mm_Pitch0.4mm i'm not really sure

I think all footprints with at least one side length smaller than 2mm might have the wrong chamfer size.

And i fear all footprints have the wrong fab line width as well. (All footprints i checked have 0.15mm instead of 0.1mm) Some sort of script might be a good idea to fix this.
---

DFN-14-1EP_3x3mm_Pitch0.4mm
you removed the solder paste margin for the ep pads. I think this margin is needed to get better results when reflow soldering.
Similar with DFN-8-1EP_6x5mm_Pitch1.27mm_LargeFlag, DFN-8-1EP_6x5mm_Pitch1.27mm_SmallFlag, Texas_PVQFN-N40 and Texas_PVQFN-N40_ThermalVias (*)

Same with DFN-8-1EP_4x4mm_Pitch0.8mm. (0.2% solder paste ratio might not have been correct either.)

*) Texas_PVQFN-N40_ThermalVias: is it a good idea for the back side pad to have mask enabled?

[Additional information from](http://www.nxp.com/docs/en/application-note/AN1902.pdf)
The segmented PCB design facilitates the solder paste flux outgassing during reflow, thereby promoting a lower voiding level of the completed solder joint. At the same time, the maximum size of a single solder void is limited by the dimensions of a single matrix segment.

---

Why did you move pad 15 of Linear_DE14MA

Does Microchip_8E-16 need a separate 3d model or would the QFN-16-1EP_4x4mm_Pitch0.65mm model be ok. (You changed it to Microchip_8E-16)

ROHM_DFN0604-3:
wrong fab line width, make clearance between pin 1 marker and pad larger.
What about a pin 1 marker on fab?

**Comment by Shackmeister** [comment]
do you refer to Pin 1 marker on Fab or Silkscreen?
the Fab line thickness should be easily fixed

I didnt think the paste margin was allowed in the footprints, Ill revert these things.

the reason why I moved the pad 15 was simply because it didnt comply with the datasheet (and caused a Tracis error)

ROHM Ill have a look at

**Comment by poeschlr** [comment]
> do you refer to Pin 1 marker on Fab or Silkscreen?

fab

**Comment by Shackmeister** [comment]
Im gonna add the UDFN in a seperate PR and do the KLC's from another PR

**Pull request closed without merging**
