### PR TITLE
Create ST_UFQFPN-20_3x3mm_Pitch0.5mm

### PR DESCRIPTION
**Pull request by evanshultz**
Fix of https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/7.

Package info on pages 94-95 at http://www.st.com/resource/en/datasheet/stm8s003f3.pdf.

Changes:
- Renamed to ST specific and no EP
- Improved description
- Fixed 3D model path
- Fixed 3D model location, rotation, and scale
- Set SMT attribute
- Added refdes on F.Fab
- Add lines on F.Fab and F.SilkS like existing 3x3mm QFNs
- Corrected pad sizes and shapes (had to guess a bit to try and match datasheet for weirdly-shapes pads)

Image:
image

The weird "points" in the mask are due to the construction of the corner pins using a rectangle, a square, and a trapezoid. If there's a better way please advise. Here is what I have:
image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Suggestion: If you disable the 'mask' layer on the small triangular part of the pad, the mask from the other parts should overlap it anyway, and the corner artifacts will disappear?

**Comment by evanshultz** [comment]
@SchrodingersGat Thanks for the great idea! I changed the mask on the trap pads to 0.001mm (basically gone). Now it looks like this:
image

That is will the default 0.2mm mask clearance. The little holes in the mask in the corners should be fine, since that will result in copper that is not exposed (and thus safe from shorting). In my experience, if the board house can't fill some geometry they ask me; even if the mask was extended over those openings it should be no problem.

And here is when I turn the board mask clearance down to 0.1mm:
image

Since this particular footprint doesn't need mask to envelop the pads, I suspect this will be OK. Other suggestions?

**Comment by SchrodingersGat** [comment]
Just as a thought, what if the corner pads, instead of being trapezoidal, were instead rectangular, and you simply overlap them and rotate them? That way the mask is also rectangular and you shouldn't get the weird corner spikes...

**Comment by evanshultz** [comment]
@SchrodingersGat That could work. I tried it on pad 20:
image

image

You can see that there's still a small dot of mask inside the corner of the part, but it now has a bevel instead of a normal square. Having normal mask clearance on all pads seems better and more maintainable, so I prefer this style than that above with tiny clearance on trap pad. Please let me know if you prefer this style too and I'll update the footprint.

**Comment by evanshultz** [comment]
I just realized that a few packages in the TO_SOT_Housings_SMD library have weird spikes on the mask layer too:
image
image

**Comment by evanshultz** [comment]
@SchrodingersGat Can you take a look at the above? You had some good ideas, but to me they're six to one and half a dozen to the other. If you have a preference or another idea, and it's not the latest push, please let me know so this can get merged.

**Comment by SchrodingersGat** [comment]
I prefer the second option, with the rectangular pad that is rotated 45 degrees. I also think you should add some small mask-only pads to cover those four holes, as this could cause issues for component placement.

**Comment by evanshultz** [comment]
OK. Pushed a version with rotated squares for the bevel (and some other fixes). I also added mask, but I'm not sure of the best size/orientation/etc. since the PCB can dictate the mask clearance and these are fixed patches of mask that grow that that dimension. Is this OK?

Mask pads:
image

Footprint when placed on a board with the default (I believe) 0.2mm mask clearance:
image

**Comment by SchrodingersGat** [comment]
> OK. Pushed a version with rotated squares for the bevel (and some other fixes). I also added mask, but I'm not sure of the best size/orientation/etc. since the PCB can dictate the mask clearance and these are fixed patches of mask that grow that that dimension. Is this OK?

If you specify the mask expansion for these pads as non-zero (e.g 0.001mm) then it will not be overridden by any PCB options, so I think doing that would be a good idea.

**Comment by evanshultz** [comment]
Updated. Here you can see how the mask square just barely covers the hole with the default 0.2mm mask clearance. My concern above, however, is that the user can control the mask clearance on the board which could result in patches of no mask again. It probably covers most of the cases since I suspect most users never touch the default, but it's less than ideal (if we could only draw polygon zones for pads...).
image

Anything else, Oliver?

**Comment by SchrodingersGat** [comment]
Polygon pads are on their way, and should be here by v5. Until then, this looks good. Thanks for your work :)

**Pull request merged**
