### PR TITLE
Added DFN-10 2x2mm package (no exposed pad)

### PR DESCRIPTION
**Pull request by SchrodingersGat**
eg

dfn

### CODE REVIEW

**Comment by pointhi** [comment]
why do you use a different silkscreen design as used for the other DFN footprints?

**Comment by SchrodingersGat** [comment]
Because I like to make things difficult! I've fixed it to match the style of the other footprints.

**Comment by pointhi** [comment]
I think you can place the courtjard much more towards the pads to save space

**Comment by SchrodingersGat** [comment]
Good idea, done.

**Comment by SchrodingersGat** [comment]
@jkriege2 KLC fixes applied to this one too

**Comment by jkriege2** [comment]
Also here I think the courtyard should be closer (0.25mm)
JAN

**Comment by SchrodingersGat** [comment]
Courtyard fixed @jkriege2

**Comment by SchrodingersGat** [comment]
@jkriege2 passing KLC with new scripts. Any comments? :)

**Comment by evanshultz** [comment]
@jkriege2 Can you please review?

**Comment by poeschlr** [comment]
@SchrodingersGat do you know what datasheet you used to design this footprint? (It should be added to the description and it would help for checking if the footprint is correct.)

The 3d settings should be filled out.
Courtyard clearance is larger than 0.25mm
Silk clearance is smaller than 0.2mm (I think for such a small part we could accept it. If we decide to make such an exception we should not that in the KLC)

**Comment by SchrodingersGat** [comment]
@poeschlr sorry this was so long ago, not sure of the datasheet :|

Made the other changes, though.

**Comment by poeschlr** [comment]
Wrong 3d model name (Wrong pitch and why step?)

**Comment by SchrodingersGat** [comment]
@poeschlr wow ok not sure how I managed that. I was up way too late when I did this. Thanks for spotting my mistake.

**Comment by poeschlr** [comment]
Well travis spotted it. 
Thanks for this contribution.

**Pull request merged**
