### PR TITLE
preparing for new 3d models

### PR DESCRIPTION
**Pull request by Shackmeister**

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Mostly ok. The _SmallFlag and _LargeFlag variants of DFN-8 should use the same model as the package dimensions do not change. Please revert these two files. The rest looks ok.

**Comment by Shackmeister** [comment]
The models I made have a different Epad but I can delete the two

**Comment by Shackmeister** [comment]
Would you prefer if I revert them to use the same model?

**Comment by SchrodingersGat** [comment]
As these models are mechanically the same size (correct?) I think it is better to reduce the number of models / file size for the sake of the repository :) Sorry!

**Comment by Shackmeister** [comment]
Indeed correct, I'll fix it in a moment :)

**Comment by SchrodingersGat** [comment]
Great work, thanks

**Comment by Shackmeister** [comment]
all the parameters have been made but will need some additional checking by Maurice who wil make the PR to the repo

**Pull request merged**
