### PR TITLE
add AMS_QFN-4-1EP_2x2mm_Pitch0.95mm footprint

### PR DESCRIPTION
**Pull request by ChristianHirsch**
@poeschlr added new footprint based on [ENS210 Datasheet](http://ams.com/eng/content/download/950231/2267959/483138)
image

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
1. Please add `AMS_` prefix
1. The pin numbering (according to your picture) is incorrect.

**Comment by ChristianHirsch** [comment]
Hi @SchrodingersGat fixed everything you mentioned :)

**Comment by SchrodingersGat** [comment]
@ChristianHirsch the datasheet shows the recommended stencil design on p31. Can you update the footprint to match these requirements? This will require some adjustments to the F.Paste layer in particular. Please let me know if you need any assistance with this. Thanks.

**Comment by ChristianHirsch** [comment]
@SchrodingersGat I think I need your assistance: I used the net pad clearance for pads 1-4, is this correct? If yes, I don't know how to apply this to pad 5. If no, could you please tell me what I really need to do? Thanks :)
image

**Comment by poeschlr** [comment]
The net pad clearance does not control solderpaste stencil opening. (I think you can keep it equal to 0) Have a look at page 31 of you datasheet and set your pads up such that you can create the recommended stencil opening.

I think the best option would be to only have one pad with number 5 of size 0.7x1.6mm. This pad has only top mask and copper enabled. (remove the tick for paste) Place a second paste only pad (disable copper and mask) on top of this pad. This paste only pad has the size 0.35x0.8mm. (Either give this paste only pad no pin number or the same pin number as the exposed pad)

For the other 4 pad simply set the paste clearance equal -0.05 (found in the pad settings -> local clearance and settings tap -> solder paste clearance)

**Comment by ChristianHirsch** [comment]
Thanks @poeschlr for your help! I applied your changes, but now I'm violating rule 8.3 and 10.3.

**Comment by poeschlr** [comment]
Yes paste only pads create problems with travis. These errors can be ignored.

**Comment by poeschlr** [comment]
The courtyard clearance looks a bit small to me. Is there a reason for it?
To get 0.25mm you would need a rectangle from (-1.5,-1.25) to (1.5,1.25)
Yours is from (-1.4,-1.2) to (1.4,1.2) which results in a clearance of 0.15 in x direction and 0.2 in y direction.

**Comment by ChristianHirsch** [comment]
You are right @poeschlr, I took a clearance of 0.15, and the reason it was 0.2 in y direction was because I took the width of the component outline into account..
Anyway, it is fixed now.

**Comment by poeschlr** [comment]
Thanks for your continued contributions

**Pull request merged**
