### PR TITLE
added Texas_S-PVQFN-N36

### PR DESCRIPTION
**Pull request by Shackmeister**
http://www.ti.com/lit/ds/slvsba5d/slvsba5d.pdf
texas_s-pvqfn-36

### CODE REVIEW

**Comment by Shackmeister** [comment]
@evanshultz Hi can you please check last update?

**Comment by Shackmeister** [comment]
@evanshultz Hi can you please have a look at this? :)

**Comment by evanshultz** [comment]
Of course! Sorry that I missed this earlier.

Here's what I see:
- The datasheet requests a 0.07mm mask oversize on pins 1-36, but I don't see that in your footprint.
- Can you improve the description? Add footprint details there, similar to the tags.
- I like to put the ref des and footprint name at equal Y axis locations, but that's just my OCD.

**Comment by Shackmeister** [comment]
@evanshultz should be CDO compliant :) can you check it again?

**Comment by evanshultz** [comment]
@Shackmeister 
Thanks for updating! They're now both at the same Y location and on the X axis origin, but they're far from the footprint. Can you move them closer to the courtyard? I realize that's minor, but it's consistent with other footprints where the text is just a few tenths of a mm from the courtyard.

**Comment by Shackmeister** [comment]
@evanshultz I just misunderstood when you said "equal Y axis  location". For some reason I thought you meant it needed to be an int/a whole number.. Me being silly, should be fixed now

**Comment by evanshultz** [comment]
Thanks!

**Comment by Shackmeister** [comment]
Thx :) being a librarian is all about slight OCD :p

**Pull request merged**
