### PR TITLE
added WSON6 package

### PR DESCRIPTION
**Pull request by jkriege2**
see http://www.ti.com/lit/ds/symlink/tlv702.pdf

wson

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Please match the rotation with the other parts in the lib (pin-1 = top-left)

**Comment by jkriege2** [comment]
fixed!
JAN

**Comment by SchrodingersGat** [comment]
Hmm I only just noticed that this naming is not "conventional" (with regard to the other parts in the lib.). Can you add dimensions and pitch? :)

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
