### PR TITLE
Modify  Texas_WQFN-MR-100 EP for stencil and add a Thermal vias version

### PR DESCRIPTION
**Pull request by jjuyon**
Hi,
Since #36, I modified the Exposed Pad for stencil layout recommendation and added a version with Thermal Vias

### CODE REVIEW

**Comment by poeschlr** [comment]
The modified Texas_WQFN-MR-100 is not included in this pull request.

The documentation field should really include more than just the link to the datasheet.
For the thermal vias version maybe include the information that you chose the 3x3 dap stencil pattern.

**Comment by jjuyon** [comment]
Ok so I added more documentations in the two component, I renamed both to add `3x3-DapStencil` pattern.
The check don't pass because of `Pad A53 annular ring (0.05mm) is below minimum (0.15mm)`. This concern the thermal vias, but I don't know what this error means !

**Comment by poeschlr** [comment]
annular ring (the minimum copper around the final hole diameter of a plated through hole)
In short: increase the x-size of your "vias" to 0.5mm to reach 0.15mm annular ring. (If possible otherwise make it as large as possible and we make an exception here.)
screenshot from 2017-06-30 12-28-38

**Comment by jjuyon** [comment]
Ok. Thanks for the explanation. As the pads are within the Exposed Pad it doesn't change to make them bigger.
I still have an error  about the thermal bottom pad I added without Paste of course. Maybe I should remove this pad to let the possibility of the user to add it or not in the PCB?

**Comment by SchrodingersGat** [comment]
Priority should always be to match the datasheet. If a variation is needed (e.g. no copper to support routing) then this should be appended e.g. `_NoEP`. 

In this particular case my suggestion would be:

1. Add a footprint without thermal vias

2. Add a variant with thermal vias (as per the datasheet) with the suffix `_ThermalVias`

3. If you want, add a version without any exposed pad wih the suffix `_NoEP`

Rather than making a stylistic ruling on how we should design footprints, go with the datasheet and make adjustments from there

**Comment by SchrodingersGat** [comment]
I have added some descriptive text to the KLC about exceptions to the layers rule. I will look into the KLC scripts and see if their output can be improved here.

**Comment by jjuyon** [comment]
Actually there is already a version without thermal vias. This is concern a bottom EP I added in combination of the thermal vias. I then removed this bottom EP and keep thermals vias.

**Comment by SchrodingersGat** [comment]
I'm confused. Correct me if I am misreading your comment, but how would thermal vias work if there was no pad for the exposed metal of the package to be soldered to?

I see the use for three variants:

1. Exposed Pad, with thermal vias
1. Exposed Pad, without thermal vias
1. No exposed pad, no thermal vias

**Comment by jjuyon** [comment]
In fact you have Exposed Pad on top  layer (F.Cu) on both. But for the thermal vias version I had also added an Exposed Pad on bottom layer (B.Cu) for explicit ground plane connection and solder mask opening but of course without solder paste layer. And This pad without solder paste doesn't passed the checker script.
So I removed it.

I was inspired by other components in the library like `Texas_PVQFN-N40_ThermalVias` witch have this Bottom Exposed Pad without solder paste layer.

**Comment by SchrodingersGat** [comment]
Oh, sorry I missed the reference to the fact that this EP was on the **bottom** of the PCB.

In that case, I am sorry to interrupting - @poeschlr had the right idea here. 

We should definitely add some information about this to the KLC description.

Thanks for your wok @jjuyon

**Comment by jjuyon** [comment]
Ok.
So should I add the bottom EP even if it doesn't pass the checker or should I keep it removed?

**Comment by SchrodingersGat** [comment]
You can keep it removed. We'll have to look into making this particular KLC checker script more intelligent to cases such as this.

**Comment by evanshultz** [comment]
I agree. No pad on the bottom of the PCB should be fine. Users can add it if they want.

**Comment by poeschlr** [comment]
Nice work. Thanks for your contribution.

**Pull request merged**
