### PR TITLE
Created UFQFPN-20-1EP_3x3mm_Pitch0.5mm.kicad_mod

### PR DESCRIPTION
**Pull request by alex4men**

### CODE REVIEW

**Comment by pointhi** [comment]
* Please mark pin 1 (I would suggest you to use a silkscreen like used by the UQFN footprints)

Also, could you please note in this PR, what footprint reference you used to draw this footprint

**Comment by alexfomenko** [comment]
I've used QFP footprint wizard first and then corrected it according to the STM8S003F3U datasheet.

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: UFQFPN-20-1EP_3x3mm_Pitch0.5mm
  Violating Rule 10.5
    Attributes is set to the appropriate value, see tooltip for more information.
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
  Violating Rule 6.3
    For through-hole components, footprint anchor is set on pad 1.
```

**Comment by SchrodingersGat** [comment]
Closed and reopened so that automated scripts test it

**Comment by hackscribble** [comment]
Hi @alex4men I'm reviewing your PR for the STM8S003F3U that uses this footprint (https://github.com/KiCad/kicad-library/pull/382).

Question for @SchrodingersGat about the naming of this footprint.  The ST datasheet calls it the `UFQFPN20`.  I can only find this particular variant of the 20-pin QFN (i.e. this specific pad layout) in ST datasheets.  Therefore, I'm wondering if it should be named `ST_UFQFPN20`?

If it stays as a manufacturer-independent name, there's a small change needed anyway to `UFQFPN-20_3x3mm_Pitch0.5mm` since it doesn't have an exposed pad.

image

**Comment by evanshultz** [comment]
@alex4men While it's been more than a year since you contributed this footprint, are you still willing to make the changes that will bring this footprint to compliance with the KiCad library requirements? If so, we'd be happy to add this footprint to the library.

**Comment by SchrodingersGat** [comment]
@hackscribble given the non-uniform nature of the pads as called out by the datasheet I suggest that yes, this should be manufacturer specific.

**Comment by evanshultz** [comment]
@alex4men If I don't hear from you in a day I will consider this PR abandoned.

**Comment by evanshultz** [comment]
@hackscribble 
Since you self-assigned this PR I don't want to be out of line. If you don't object, I'm going to close this PR and then pull this footprint, fix it up, and make another PR. Please let me know if that's OK with you.

**Comment by hackscribble** [comment]
No problem :smile:

**Pull request closed without merging**
