### PR TITLE
Add QFN-48-1EP_6x6mm_Pitch0.4mm

### PR DESCRIPTION
**Pull request by slowcoder**
First footprint PR.

This footprint is used by the symbols in KiCad/kicad-library#1566
qfn48

Datasheet: https://www.onsemi.com/pub/Collateral/485BA.PDF

### CODE REVIEW

**Comment by evanshultz** [comment]
@slowcoder 
Thanks for submitting this footprint and continuing the contribute to KiCad!

It's great that you added the image of the footprint. Please also make a link to a related PR (like https://github.com/KiCad/kicad-library/pull/1566) instead of just text. Also, please include a link to the datasheet in each PR for simplicity. http://infocenter.nordicsemi.com/pdf/nRF51822_PS_v3.1.pdf is suitable.

Review comments:
- In the description, include the full URL to the datasheet
-  Add pin pitch in the description
- The courtyard should be outside the extents of the package or copper by 0.25mm on a 0.01mm grid
- Silkscreen must be outside the part body, so not overlaid with the fab lines
- Fab lines should mark pin 1 with a bevel corner
- You have the ref des on F.Fab twice; only use one in the center of the part
- Typically there will be multiple cutouts in the stencil for paste; here the stencil is a huge hole

Rules for footprints can be found at https://github.com/KiCad/kicad-library/wiki/Kicad-Library-Convention. Please read them and review the existing QFN packages which will an excellent reference. If you have questions, please ask, and until then I'm looking forward to seeing your updated footprint!

**Comment by slowcoder** [comment]
Alright. I think I got all (but one) of your feedback taken care of. First PR is always a bit of a pain. :)

The only one I can't figure out is the paste stencil. I have all the clearances set to 0 (as indicated by KLC), and I can't really figure out how to change this.  Any advice/tips ?

**Comment by evanshultz** [comment]
I forgot something important in my last message. The Nordic Semi datasheet only shows a package drawings, but not a PCB footprint. How did you design the PCB footprint? If this isn't available online, nor in the datasheet, you may need to contact Nordic Semi.

The stencil can be tricky. Right now pad 49 has F.Cu, F.Mask, and F.Paste layers. It should not have F.Paste since the stencil will drive that layer. (A clearance of 0 on the big copper pad is correct since it doesn't have the F.Paste layer.) Then you create multiple rectangles on the F.Paste layer only (!) which cover some percentage (usually 70-90%) of the big copper pad. Look at other QFNs in the library for an example; QFN-48-1EP_7x7mm_Pitch0.5mm is close to yours. However, the number and size of the stencil openings is determined part-by-part, and so we need the info I requested above to know how it should be constructed.

More review:
- Instead of rotating pads, flip the X and Y dimensions. It doesn't change 180 degree rectangular pads.
- The courtyard should be 0.25mm from copper/body. Make it 3.45mm square with the current pads.
- I like to have the ref des and F.Fab footprint at equal Y locations, but I will merge like this.
- The description can be simplified to `48-Lead Plastic QFN, 6x6mm, 0.4mm pitch (see http://infocenter.nordicsemi.com/pdf/nRF51822_PS_v3.3.pdf)`.

**Comment by slowcoder** [comment]
Well, fudge.  I can't even remember where I got the dimensions from. I've had this footprint in my local library for well over a year..

I do however have a point-of-contact at Nordic, so I can ask them, but that'll most likely take until Monday until I get a response.

**Comment by slowcoder** [comment]
Ok, I'm back!

I've spoken to an actual engineer at Nordic, and they (seriously) don't have any recommendations except "look at our gerbers, they seem to work".  In addition to that, they refer to IPC-7351, which I have familiarized myself with, but it doesn't seem to specify much for QFN packages, except the recommended solder-mask clearances..
So, I don't really know what to do about that. I can tell you that this is a footprint that I've used, and it works fine for automated assembly, as well as hand-soldering (assuming you have a decently small tip).

I also have a question about your review w/ regard to the stencil.
Are you saying that I should (more or less) draw on the paste-layer, and not use the paste-layer in the pad properties?   Is that just for pad 49, or all pads?
Also, when you said "here the stencil is a huge hole", how do you see that? 

 Also, is it worth continuing this PR without any worthwhile recommendations from the manufacturer?

**Comment by poeschlr** [comment]
Regarding stencil:

Normally the paste layer (for pad 49 only) should be broken up into multiple smaller squares.
For most components this information is given in some sort of application note)
Example for such an application that gives details on this (one for a qfn package by TI)
http://www.ti.com/lit/an/sloa122/sloa122.pdf

A better more detailed application note (the interesting part is on page 5 and page 6)
http://www.psemi.com/pdf/app_notes/an62.pdf

> It is a good practice to minimize voids within the exposed pad interconnection, so the design of the exposed pad stencil is crucial. The proposed stencil design enables out gassing of the solder paste during reflow and also regulates the finished solder thickness. Typically, the stencil apertures are reduced such that the solder paste coverage is 50% to 70% of the  exposed pad area.

**Comment by evanshultz** [comment]
@slowcoder Can you find another datasheet for the same package? Many IC packages are produced by a small number of companies, like Amkor, so you can often find another supplier that selected the same package. This particular package seems like it should be common in the semiconductor industry.

**Comment by slowcoder** [comment]
Would using something like this: http://www.ipc.org/ContentPage.aspx?pageid=Land-Pattern-Calculator to get the dimensions be acceptable?

I managed to get it to split up pad 49 into four smaller pads on the paste layer, so it seems to do what you're asking for.

**Comment by evanshultz** [comment]
Using IPC tools is often a good way to go. What do you get for this part? How does the IPC calculator compare with similar QFNs? If it gives similar results to a datasheet you can find online, and the same or close to what you have which you said has been used successfully, then I'd feel pretty comfortable with IPC's footprint.

**Comment by slowcoder** [comment]
Well, did the changes, and the checking scripts hate me for it...

I'm at my wits end here. I'm about to give up and close the PR(s)..

**Comment by SchrodingersGat** [comment]
Hi @slowcoder please don't be disheartened :) There is a major shortcoming in the KLC scripts which throw errors when you have pad-settings that are "non-standard". This needs to be addressed but in this case, where you have a specific reason for making the pads in such a fashion, these "errors" may be ignored.

**Comment by evanshultz** [comment]
@slowcoder 
Sorry this is frustrating. Yes, right now you can't make KLC happy when the footprint is correct.

When you provide a major update, please include a fresh image of the footprint. This will make checking the changes faster and easier.

Feedback:
1. Do you have any output from the IPC tool, if you used it. What did you find?
1. I still would like a footprint reference. Were you able to find a footprint for an identical package?
1. Line 82 is a stencil opening but the pad is numbered 49.
1. Ref des and footprint name are both above the footprint. Put the footprint name below.

**Comment by evanshultz** [comment]
@slowcoder Can you answer the questions above? Thanks!

**Comment by evanshultz** [comment]
@slowcoder Are you able to update this footprint?

**Comment by slowcoder** [comment]
1. There were no machine-readable output from the IPC tool, so I measured in their tool and transcribed it best as I could
2. No landing-patterns unfortunately. I found two similar footprints though;
  http://www.intersil.com/content/dam/Intersil/documents/l48_/l48.6x6.pdf
  https://www.onsemi.com/pub/Collateral/485BA.PDF
3. Fixed
4. Fixed

**Comment by evanshultz** [comment]
@slowcoder 
Thanks for finding this information. The Intersil and On Semi have tiny differences, but otherwise they're compatible packages and also compatible with the Nordic Semi package.

The On Semi footprint shows the largest pads which should work for all parts. Please update your footprint to match that drawing. And also change the link in the footprint description to point to that document instead of the Nordic Semi one. Thank you!

**Comment by evanshultz** [comment]
Change the "20" to "10":
image

**Comment by evanshultz** [comment]
Thanks for updating.

Unless my math is wrong, pin 1 should at (-2.86,-2.2). The 2.86 comes from 6.4mm / 2 - 0.68mm / 2. Yours are at (-2.94,-2.2). Please move the pads to the location or else point out what I'm calculating wrong.

Also, the stencil openings over pad 49 look awfully large. Can you review existing footprints and see if something is more suitable? There are some other 6x6mm QFN footprints that have smaller stencil openings but more of them, and this will be better for soldering.

**Comment by evanshultz** [comment]
@slowcoder Are you able to finish off this PR?

**Pull request closed without merging**
