### PR TITLE
UDFN-4_1x1mm_Pitch0.65mm_ThermalVias

### PR DESCRIPTION
**Pull request by Misca1234**
What do you think about this one

Microchip use it and call it "4-Pin 1mm x 1mm Thin DFN (MT)"
Page 13 http://ww1.microchip.com/downloads/en/devicedoc/mic550x.pdf

Diodes use it and call it "X2-DFN1010-4"
https://www.diodes.com/assets/Package-Files/X2-DFN1010-4.pdf

Onsemi use it and call it "UDFN4 1.0x1.0, 0.65P"
Page 17 http://www.onsemi.com/pub/Collateral/NCP114-D.PDF

They are all almost identical except that 
Microchips central pad 0.48x0.48
OnSemi's central pad is 0.58x0x58
Diodes says its central pad is 0.48x0.07 but i guess it is an error and should be 0.48x0.47

So I decided to call it 
UDFN-4_1x1mm_Pitch0.65mm_ThermalVias and set the central pad to 0x48x0.48
and placed it in Housings_DFN_QFN.pretty

Each pad is built up by 3 elements where two of them overlap the larger rectangle one.

I choose not to have a thermal vias drill hole in the centre pad because I guess 
it gets to big, or should I add one anyway ?

bild

bild

bild

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Hi @Misca1234 this generally looks pretty good.

1. You have named this `_ThermalVias` but it does not have thermal vias
1. Does any datasheet recommend thermal via placement?
   1. If so, add versions with and without thermal vias.

**Comment by Misca1234** [comment]
I guessed that any footprint with a (thermal) pad, with or without vias underneath should have the suffix ThermalVias but I remove the suffix.

**Comment by Misca1234** [comment]
The suffix ThermalVias is removed


bild

**Comment by Misca1234** [comment]
Nice, thx

**Pull request merged**
