### PR TITLE
Added SONP-8

### PR DESCRIPTION
**Pull request by SG-O**
Based on Texas Instruments CSD18531Q5A http://www.ti.com/lit/ds/symlink/csd18531q5a.pdf

### CODE REVIEW

**Comment by poeschlr** [comment]
This footprint should go into the Housing_SON library (https://github.com/KiCad/Housings_SON.pretty)
Please reference this pull request when you open your new PR in the correct repo.

For the exposed pad:
The large pad should not have paste added. The four small pads should only add paste.

Otherwise the footprint looks good.

**Comment by SG-O** [comment]
Sorry for using the wrong library, I will open a new pull request once I fixed the thermal pad issue.
I tried removing the copper from the paste pads and paste from the large pad but then the footprint check script complained about it. So I removed the paste by setting the solder paste ratio clearance to -50%. 
What should I do about that?

**Comment by evanshultz** [comment]
It's OK to have violations of the check script for this. The scripts don't currently handle this condition well.

**Comment by poeschlr** [comment]
Removing paste is done by "unticking" the paste layer
Left half shows the settings of the single big copper pad. It is responsible to add copper and the solder mask cutout. (Give it the correct pin number)
The right setting should be used for the 4 paste only pads. (Remove the pin number from this 4 pads)
pads for ep

**Comment by SG-O** [comment]
Moved to Housing_SON (https://github.com/KiCad/Housings_SON.pretty/pull/14)

**Pull request closed without merging**
