### PR TITLE
Added refdes on fab layer to QFN-32-1EP_4x4mm_Pitch0.4mm

### PR DESCRIPTION
**Pull request by aliteke79**

### CODE REVIEW

**Comment by poeschlr** [comment]
The reference is a bit small (and the font would be to thick. The line thickness should be 15%)
I would suggest a font-size of 0.7 and a line width of 0.1.

**Comment by aliteke79** [comment]
I did it, thank you.

**Comment by aliteke79** [comment]
Sure, i have uploaded.

**Comment by poeschlr** [comment]
Thanks for this nice fix. (The footprint looks a lot better now.)

**Pull request merged**
