### PR TITLE
added versions of some QFN-24 footprints without exposed pad

### PR DESCRIPTION
**Pull request by hyOzd**
These footprints are intended to be used with MEMS motion sensor ICs. Exposed pads are removed per manufacturers recommendation.

epad

Specifically I've added these footprints to use them with symbols in this [pull request](https://github.com/KiCad/kicad-library/pull/652). Please see the thread for more info.

Notes: 
* other than exposed pads I've only changed the courtyard of the 3x3mm part which wasn't on the 0,05mm grid. 
* I had a violation on 4x4mm part's 3D file because its name is not the same as the footprint name. This footprint definitely doesn't require a different 3d model.  Can we ignore the warning for this case?

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@hyOzd if you completely remove the ePad from the footprint, won't that solve the problem also? There will still be soldermask under the part, but as there is no copper there, it will be lower than the pads and result in a small gap underneath the part.

In this case you could simply delete the inner pad and call it *QFN-24_3x3mm_Pitch0.4mm.kicad_mod*

**Comment by hyOzd** [comment]
@SchrodingersGat My worry is that in some cases solder mask thickness can be more than copper thickness. I don't have much experience with pcb manufacturing but lets look at this example from [OSH Park's stack up](http://docs.oshpark.com/services/four-layer-medium-run/);

Thickness | Layer |Tolerance
--------------|--------|----------
1 mil |solder resist |+/-0.2mil
1.4 mil |1 oz copper | 
6.7 mil |FR408 prepreg |+/-.67mil
0.7 mil |0.5 oz copper | 
47 mil |FR408 core |+/-4.7mil
0.7 mil |0.5 oz copper | 
6.7 mil |FR408 prepreg |+/-.67mil
1.4 mil |1 oz copper | 
1 mil |solder resist |+/-0.2mil

Let's assume positive error of 0.2mil on solder resist thickness; 1.2mil is rather close to 1.4mil copper thickness. I wouldn't want to take any chances especially with cheap PCB manufacturers.

About the naming; I've just noticed the "EP" part in the component name. Now I'm thinking a name like "QFN-24EP_3x3mm_Pitch0.4mm_IsolatedPad.kicad_mod" as you suggested earlier would be better. Please let me know what do you think.

**Comment by SchrodingersGat** [comment]
There is also a certain thickness of solder paste between the copper and the pads, so that would provide some offset too.

Unless you have found an instruction that specifically says to remove the solder mask under the part, I think a version of the footprint without the exposed pad would suffice...

**Comment by hyOzd** [comment]
> Unless you have found an instruction that specifically says to remove the solder mask under the part, I think a version of the footprint without the exposed pad would suffice...

How about this? I set copper layer to None, and only enable F.Mask layer. It works but is it acceptable to library?

isolatedpad

**Comment by SchrodingersGat** [comment]
Ok I can see the value of having one of each. Here is what I propose:

Currently we have *QFN-24-1EP_3x3mm_Pitch0.4mm.kicad_mod* (as an example)

I think that you should create two variants of this:

* *QFN-24_3x3mm_Pitch0.4mm.kicad_mod* (This version simply has the EPAD removed)
* *QFN-24_3x3mm_Pitch0.4mm_NoMask.kicad_mod* (This version has the EPAD only applied to the F.Mask layer, as you have given above)

This way the user can choose. I would also suggest that in the PR for the symbols (https://github.com/KiCad/kicad-library/pull/652) you do not set a default footprint, but allow the user to choose. I would instead put a footprint filter such as *QFN\*3x3mm\*Pitch0.4mm* which would match the existing footprint AND the two new ones

**Comment by hyOzd** [comment]
@SchrodingersGat I've updated footprints and symbols according to your suggestions.

**Comment by SchrodingersGat** [comment]
Great! Only one more requirement :)

For each of the footprints, please add the package outline to the F.Fab layer (0.15mm line with 1mm bevel at top-left corner) see here https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/21

This is a new requirement, hasn't made it to the KLC yet.

**Comment by hyOzd** [comment]
Done.

**Comment by SchrodingersGat** [comment]
Great work, thanks for putting up with all the requests :)

**Pull request merged**
