### PR TITLE
Added Texas_R_PUQFN-N12 and Texas_S-PVQFN-N14

### PR DESCRIPTION
**Pull request by Misca1234**
Texas_R_PUQFN-N12_2.0x1.7_Pitch0.4mm
Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod

from  http://www.ti.com/lit/ds/symlink/txb0104.pdf

bild

bild

### CODE REVIEW

**Comment by poeschlr** [comment]
First of all, thanks for your continued efforts to improve our lib. I appreciate it.

Now to the footprints.
I think these extra lines you have on the courtyard layer should go to the silk layer. (on the courtyard layer place only the rectangle that tells the user how much space is needed.)

I assume these go with the 3d models of
https://github.com/KiCad/packages3D/pull/66
If so i think there might be a problem with both footprints.

Texas_R_PUQFN-N12_2.0x1.7_Pitch0.4mm should be rotated by 90 degree such that pin 1 is on top left.
screenshot from 2017-06-12 01-12-18

Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod: Either the footprint or the 3d model has the wrong position for the pins 1, 14, 7 and 8
screenshot from 2017-06-12 01-12-58

**Comment by Misca1234** [comment]
Yes, I have noticed it as well, i just made the same mistake with the other 3 BGA packages in progress that I have not pushed yet, I will shortly push an update for these two footprints.

About the Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod
It might be a problem here, because the cadquery expect same distance between the pins, all the way around, in this case 0.5 but the footprint from the data sheet places these 4 pins on a distance of 0.75 from centre line, I probably have to manually move them

**Comment by Misca1234** [comment]
Texas_R_PUQFN-N12_2.0x1.7_Pitch0.4mm
I failed to meet the design rule of placing pin 1 closest to top left, that explain the rotation

**Comment by poeschlr** [comment]
Maybe @easyw or @shackmeister  know of a trick on how to place these four pins in the 3d model.

**Comment by Misca1234** [comment]
No, it is ok, I changed the step between the pins from 0,5 to 0.25 and excluded a lot more pins

**Comment by Misca1234** [comment]
I have checked that the 3D models are correctly aligned, do you want the 3D models now or should we finish all the footprint first ?
bild
bild

bild

bild

**Comment by poeschlr** [comment]
Texas_R_PUQFN-N12_2.0x1.7_Pitch0.4mm
Pin 1 looks like an "L" according to datasheet. (This should be reflected in the pad.)
To solve this place a second pin 1 pad at the "_" part of the "L" (Make sure this second pad has the same pin number as pin 1 and it overlaps with the current pin 1. Touching is not enough the pads need to overlap.)
txb0104

Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod
The thermal pad should not have solder paste across the whole pad. Either remove the paste from the large pad and place 4 paste only pads on top.
Or delete the large pad and create 4 separate pads with the correct paste clearance settings. (If my math is correct this is not an option for this footprint because it would require different clearances for different directions of the pads.)

Note to myself: Rounding over the inner "edge" of the pads is not necessary. (Other QFN footprints in this lib don't have this feature either.)

For both footprints:
I would also suggest to reduce the length of the "bottom" silk line (the one that is not near pin 1)
This would make it more clear where pin 1 is located.
For inspiration: DFN-14-1EP_3x3mm_Pitch0.4mm and DFN-12-1EP_2x3mm_Pitch0.45mm

**Comment by Misca1234** [comment]
Changed F.silk markings for pin 1, added the L shape for pin 1 and removed the paste layer for the back and front large thermal pads


bild

bild

**Comment by Misca1234** [comment]
I can not get it passed the travis test script so I made the thermal pads and holes equal to footprint 
Texas_PVQFN-N40_ThermalVias

**Comment by poeschlr** [comment]
Just for your information: if you have a legitimate reason why travis gives a warning we will still accept your contribution. (Travis is mainly here to help us find possible problems.)

I would make this footprint similar to this (remove txt file ending to import it into your library. Do not copy it into your lib use the import function!)
[Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod.txt](https://github.com/KiCad/Housings_DFN_QFN.pretty/files/1076291/Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod.txt)
Travis will complain of course. It will complain that the main pad 15 does not have paste activated. 
It will complain that the 4 paste pads don't have copper activated. 

It will also complain that the "vias" have the mask layer deactivated on the back side.
To test this just place vias into a similar pad and look what the gerber export makes of them. You will discover that normally the vias are covered by the solder mask. (option "do not tent vias" controls if the vias are covered or blank) Not all manufacturers like this though.

@SchrodingersGat or @jkriege2 can one of you take over the responsibility of merging this. (I now am to involved for an independent opinion.)

**Comment by SchrodingersGat** [comment]
Hi @Misca1234 a couple of suggestions here:

1. When providing manufacturer specific IC footprints, the dimensions / pitch information can be omitted
2. The format should be `Manu_Pkg-id` (Underscore between manu-name and pkg-name, hyphen elsewhere)

e.g.

* `Texas_R-PUQFN-N12`
* `Texas_S-PVQFN-N14`

3. Match the datasheet in preference to KLC, when it comes to stencil / soldermasking. e.g. for `S-PVQFN-N14` the stencil aperture should be split into four sections as shown in the datsheet.

4. Thermal vias are "optional". It would be great to add a version of the FP with vias, and one without. KLC convention for this is to append `_ThermalVias` to the end of the footprint name.

5. RefDes (`REF**`) on F.Fab layer can be increased in size a bit

6. FP name and RefDes on Silk.Screen layer can be moved closer to footprint to take up less board space:

image

Thanks!

**Comment by Misca1234** [comment]
Ok, no problem

I hope i got the thermal vias correct this time

Renamed
Texas_S-PVQFN-N14_4.3x4.3_Pitch0.5mm_ThermalPad.kicad_mod
Into
Texas_S-PVQFN-N14_ThermalVias.kicad_mod
Texas_S-PVQFN-N14.kicad_mod
Changed how the ThermalVias was constructed on Texas_S-PVQFN-N14_ThermalVias.kicad_mod

Renamed
Texas_R_PUQFN-N12_2.0x1.7_Pitch0.4mm.kicad_mod
Into
Texas_R_PUQFN-N12.kicad_mod

**Comment by Misca1234** [comment]
bild

bild

bild

**Comment by poeschlr** [comment]
If you make the paste only pad the same size and position as the copper pad you would not need it.
As suggested above, make 4 such pads at the correct positions/size
Each of them is distance 0.56 from the origin in both x and y direction and has a size of 0.82 in x and y direction.

I also think that the version without the _ThermalVias suffix should still have the exposed pad. (with the special past pads)
Only the vias are removed. (The 4 through hole pads)

**Comment by Misca1234** [comment]
The therrmal pad have been added and changed 


bild


bild

**Comment by SchrodingersGat** [comment]
> NOTE, i am using the same 3D name for both the thermal and non thermal Texas_S-PVQFN-N14, is this ok, or should I create a 3D model for the ThermalVias as well ?

They should both reference the same 3D model.

Also, why did you move the second `REF**` from inside the footprint for the `Texas_S-PVQFN-N14_ThermalVias`? This should be moved back to (0,0)

**Comment by Misca1234** [comment]
Naa, my mistake, i moved it away to manipulate the thermal vias and then I was so in zoomed and took the screen shoot so i did not notice i had moved it away

**Comment by Misca1234** [comment]
Moved in the REF ** inside the courtyard lines

bild

**Comment by SchrodingersGat** [comment]
Thanks @Misca1234 for your work here :)

**Comment by Misca1234** [comment]
np, thanks a lot for your patience, I will push the 3D and schematic for the ic in mind as soon as possible
Now I know how you want the thermal vias as well so it will be a lot easier in the future.

**Pull request merged**
