### PR TITLE
Add Infineon MLPQ/PQFN footprints

### PR DESCRIPTION
**Pull request by evanshultz**
As part of https://github.com/KiCad/kicad-library/pull/1564#issuecomment-333682496, I needed to create a number of new footprints. I was finally able to get all the info from Infineon about the footprints, which has taken some time, so here are the footprints.

You will not find copper/stencil information in the datasheets, but https://www.infineon.com/dgdl/Infineon-AN1170-AN-v05_00-EN.pdf?fileId=5546d462533600a40153559ac3e51134 would ostensibly be useful. However, it contains loads of errors and unclear parts and I found it mostly worthless for making footprints. I've asked if the info I got can be released or will be included in official Infineon documentation. Otherwise, you may have to trust me and accept that the footprint documentation doesn't contain a link to a useful document. Sorry!

The MLPQ48 one has two variants, and I'm still confirming a few things about it.

**Feedback now on pin numbering and footprint names, as mentioned in the PR for the schematic symbols, would be very much appreciated.**

Image:
image

### CODE REVIEW

**Comment by evanshultz** [comment]
Fixed line endings. Notepad++ got me again.

On the MLPQ16 (14 lead) footprint I used the stencil openings recommended by Infineon under each pad. If you prefer, since they're a direct shrinkage of the copper pad size, I can eliminate this and just allow Pcbnew to control the clearance.

All other KLC violations look bogus to me. Just need to confirm with Infineon that the MLPQ48 footprint is good.

**Comment by SchrodingersGat** [comment]
For bespoke footprints such as this, directly controlling the opening size is preferred, rather than letting the footprint use default clearances.

**Comment by SchrodingersGat** [comment]
I'm happy with the look of the footprints, you've done a great job!

Once you've heard back from Infineon let me know and I'll merge.

**Comment by evanshultz** [comment]
@SchrodingersGat Thank you. What about the footprint names? Is using the full pin numbers up front, with the used pins at the end good? Or would it be better to rename `Infineon_MLPQ-16-1EP_4x4mm_Pitch0.5mm_14L` to `Infineon_MLPQ-14-1EP_4x4mm_Pitch0.5mm`, for example?

**Comment by evanshultz** [comment]
And what about pin number mismatches? For example, the PQFN-44 part actually only has 31 pins since some of them are electrically connected. Is this OK as well?

**Comment by SchrodingersGat** [comment]
Have a look at [this document](https://www.cskl.de/fileadmin/downloads/PCBLIBRARIES/Documentation/IPC-7351C-Land-Pattern-Naming-Convention_.pdf) at the top of page 4

This would suggest naming it we.g. `Infineon_MLPQ-14-16-1EP_...`

I think this would be a good way to go - we should encode this in the KLC though, I don't think we've dealt with this before.

**Comment by evanshultz** [comment]
Wouldn't it be `Infineon_MLPQ-16-14-1EP_...`? Perhaps I'm confused over the use of "hidden" versus "deleted" in that doc. But it seems like the pins are removed ("deleted") from the package and the schematic symbol only uses 14 pins.

**Comment by SchrodingersGat** [comment]
Ah yep you're right, I was reading it the wrong way around.

**Comment by SchrodingersGat** [comment]
Thanks for your contributions Evan :)

**Comment by evanshultz** [comment]
@SchrodingersGat Do you mind to un-merge this? I still haven't heard back about my last question to Infineon.

Also, what about the pin numbering I mentioned above and in the update to ir.lib? Does this pin numbering style work, even when the footprint name reflects 44 pins but the actual symbol only has 31 pins? It seems weird, and Infineon's documentation shows many interpretations, but this is the best method I found.

**Comment by SchrodingersGat** [comment]
Oh sorry I thought you were ready to go. I'll revert this now.

**Comment by SchrodingersGat** [comment]
Can you provide a specific example of where you think the pin numbering scheme in the linked document doesn't work?

**Comment by evanshultz** [comment]
I think what I've done does work! But perhaps I've missed something.

Let's look at IR43x2M. Here is the image on the first page of [the datasheet](https://www.infineon.com/dgdl/ir4302.pdf?fileId=5546d462533600a4015355d602a9181d):
image

COM is connected to the following pins: 15, 28, and 31. Since 31 is the big pad, I selected 31 for this footprint and schematic symbol.

Also, the footprint is called PQFN-44 but only pins up to 31 are used and the pin numbers are non-contiguous. PQFN-22 is similar but not as extreme.

I think this is the best way to go but I'd like feedback rather than having to go over it again.

**Comment by SchrodingersGat** [comment]
I agree that it's a bit confusing but I think the simplest way of naming this is as the link above suggests, e.g.

`Infineon_PQFN-44-31_....`

**Comment by evanshultz** [comment]
And this is correct even if less than 31 pins are used? Notice the second example on page 4 does not include "up to" in the last sentence. So it seems if the second number is smaller, it's not "up to". This is a bit weird and confusing, and we don't have to stick with what they say, but I'd rather ask and answer questions up front.

Also, I got a response from Infineon. There are two MLPQ48 footprints, one for IRS2052M and one for IRS2093M (the datasheets show the same package but they're actually a bit different). The primary difference is the thermal pad size to suit the different die and slug size. I think I'll call them `MLPQ-48_1EP_7x7mm_Pitch0.5mm_PAD5.15x5.15mm` and `MLPQ-48_1EP_7x7mm_Pitch0.5mm_PAD5.55x5.55mm`. That seems correct based on https://github.com/KiCad/kicad-library/issues/1447#issuecomment-330186427, except I explicitly put the units for the pad size. Correct?

@SchrodingersGat I thought you could revert this so I can update my branch, but it seems like this PR is merged so should I create a new one?

**Comment by SchrodingersGat** [comment]
Perhaps it was an omission to drop 'up to' in that sentence? In any case, I think it's fine, that document was only a guide...

I think I can revert my reversion which would add your changes back in. Are you now happy for me to do that?

**Comment by evanshultz** [comment]
OK. Yes, please. If you revert I can update. Thank you.

**Comment by SchrodingersGat** [comment]
Ok, reversion reverted https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/69

**Comment by evanshultz** [comment]
Should the suffix for pad size be `PAD` or `Pad`? The link I sent earlier is all caps, but elsewhere we always have used camelcase in footprint names.

**Comment by evanshultz** [comment]
Personally, I like camelcase looks much better.

**Comment by SchrodingersGat** [comment]
Camelcase - this is what I have mandated for the new library capitalization format (as yet unreleased :p)

**Pull request merged**
