### PR TITLE
Added two manufacturer-specific footprints

### PR DESCRIPTION
**Pull request by SchrodingersGat**
Originally sourced from:

* https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/10
* https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/8

Updated to match KLC requirements

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Reasons for KLC exceptions - these footprints refer to the default 3D model. So KLC can be ignored in this case.

**Comment by jkriege2** [comment]
Hi!

looks good so far. only one question: Where did you take the name 8E-16 from for the Microcip package? Googling for it, I didn't find anything (except rubbish ;-) ... see e.g. microchip https://www.google.de/search?client=firefox-b-ab&biw=1596&bih=929&tbm=isch&sa=1&q=microchip+8E-16&oq=microchip+8E-16&gs_l=img.3...1454.4808.0.4986.11.11.0.0.0.0.135.854.7j3.10.0....0...1.1.64.img..2.0.0.XfAUKqwyzmo)

Please double-check the name and rename, if necessary.

Then I will merge!

JAN

**Comment by SchrodingersGat** [comment]
Check out the [Microchip Packaging Specification](http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf) (page 268)

**Comment by jkriege2** [comment]
OK, seen it ;-)

Great work!

JAN

**Pull request merged**
