### PR TITLE
Added WQFN-16-1EP_4x4mm_Pitch0.65mm

### PR DESCRIPTION
**Pull request by Lichtso**
For DRV8833RTY see: https://github.com/KiCad/kicad-library/pull/1605

### CODE REVIEW

**Comment by Shackmeister** [comment]
please post a screenshot when making a PR :)

**Comment by Lichtso** [comment]
wqfn-16-1ep_4x4mm_pitch0 65mm

**Comment by SchrodingersGat** [comment]
Hi @Lichtso thanks for contributing

1. The footprint file must have `.kicad_mod` extension
1. Please add two versions of this footprint:
  1. One with the thermal vias and has the `_ThermalVias` suffix
  1. One without any thermal vias

Thanks

**Comment by SchrodingersGat** [comment]
Thanks for working through the issues @Lichtso :) your contributions are appreciated!

**Pull request merged**
