### PR TITLE
Create Maxim-IC_90-0059.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
according to datasheet
http://pdfserv.maximintegrated.com/land_patterns/90-0059.PDF

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@savenlid is this not the same as https://github.com/KiCad/Housings_DFN_QFN.pretty/blob/master/DFN-8-1EP_3x3mm_Pitch0.65mm.kicad_mod ?

**Comment by SchrodingersGat** [comment]
Hi @savenlid any interest in continuing with this PR?

**Comment by evanshultz** [comment]
@SchrodingersGat The exposed pad seems dramatically different in size, 1.58x2.35mm here and 0.775x1.2mm for the library footprint. There are other minor dimensional differences too.

Here is the package datasheet that goes with the footprint: http://pdfserv.maximintegrated.com/package_dwgs/21-0137.PDF.

@savenlid Are you willing to make the changes that will allow this PR to be merged? If not, please close this PR.

**Comment by evanshultz** [comment]
Closed and re-opened to trigger Travis.

Here is the package datasheet that goes with the footprint: http://pdfserv.maximintegrated.com/package_dwgs/21-0137.PDF.

@SchrodingersGat The exposed pad seems dramatically different in size, 1.58x2.35mm here and 0.775x1.2mm for the library footprint. There are other minor dimensional differences too.

@savenlid You can click the Details link above to see the results of the footprint automatic rules checker. Are you willing to make the changes that will allow this PR to be merged? If not, please close this PR.

**Comment by savenlid** [comment]
http://pdfserv.maximintegrated.com/land_patterns/90-0059.PDF

F.cu does match , but i took down the soldermask to 0.05 and removed
excessive silk
it had wrong 3D model.


T833* packages.
I made a T833 package copy also.

All to be found @
https://github.com/savenlid/kicad/tree/master/footprints/Maxim-IC



2017-07-18 22:33 GMT+02:00 evanshultz <notifications@github.com>:

**Pull request closed without merging**
