### PR TITLE
Added WQFN-32-1EP

### PR DESCRIPTION
**Pull request by SG-O**
The Footprint has been checked and there are no reported errors

### CODE REVIEW

**Comment by poeschlr** [comment]
The footprint name should include the body size.
So it should be WQFH-32-1EP_5x5mm_Pitch0.5mm

The description field should be written in a more generic way. (It should describe the footprint not one of its applications.) Giving the datasheet as you have is ok. (This after all is the datasheet used to design the footprint)

The lines on fab layer should have a width of 0.1mm

The reference on fab can be larger (fontsize 1mm) and still find place within the body. It should also be moved to (0,0).

The courtyard outline is too far away. It should be 0.25mm as measured from the pads. (edge of pad to center of courtyard line)

---

There are a few problems with the Exposed pad.
First problem: Wrong size
screenshot from 2017-08-16 13-34-59

Second problem: The paste layer should be split up to reduce solder paste coverage.
(This is the reason for having multiple pads.) This might be either specified in the datasheet directly or in an application note.
Example for such an application note
http://www.ti.com/lit/an/sloa122/sloa122.pdf

A better more detailed application note (the interesting part is on page 5 and page 6)
http://www.psemi.com/pdf/app_notes/an62.pdf
>It is a good practice to minimize voids within the exposed pad interconnection, so the design 
of the exposed pad stencil is crucial. The proposed stencil design enables out gassing of the 
solder paste during reflow and also regulates the finished solder thickness. Typically, the 
stencil apertures are reduced such that the solder paste coverage is 50% to 70% of the 
exposed pad area.

**Comment by SG-O** [comment]
If I chose a custom solder paste clearance I am violating rule 10.3 when I run check_kicad_mod.

**Comment by SG-O** [comment]
I changed the footprint according to your feedback.

**Comment by poeschlr** [comment]
Thanks for contributing.

**Pull request merged**
