### PR TITLE
Created QFN-56-1EP_7x7mm_Pitch0.4mm

### PR DESCRIPTION
**Pull request by ashtonchase**
Created QFN-56-1EP_7x7mm_Pitch0.4mm

Currently no 3D model.

### CODE REVIEW

**Comment by pointhi** [comment]
You have to remove the 3D model, or create the correct one:

```
checking module: QFN-56-1EP_7x7mm_Pitch0.4mm
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

Furthermore, please fix the silkscreen:
* no soldermask point for pin 1
* the silkscreen is too far out. Look onto other QFN footprints how this should be done
* without soldermask, the inner pads are useless in the current state

**Comment by ashtonchase** [comment]
I updated the silkscreen. 
I updated the soldermask for the inner pads. 

I'm not sure how to remove the 3D model, as I never created one to begin with. I'm assuming there is some reference that I have to remove to supress the error. Please advise.

**Comment by ashtonchase** [comment]
All comments have been incorporated.

**Comment by CarlPoirier** [comment]
Hi @ashtonchase,

I have some more comments.

First, your courtyard is too close. It needs to be 0.25mm farther than the pads, as indicated in KLC rule 6.7.

Second, the silkscreen may not protrude from the courtyard, so the pin 1 mark is not adequate. I suggest you adopt the same technique as with the other QFN footprints, that is indicating pin one by leaving out the small silkscreen segment near it.

Third, please use rectangular pads.

I hope this helps!

Carl

**Comment by CarlPoirier** [comment]
HI @ashtonchase,

Your courtyard clearance is still wrong. I'm measuring it at 0.35mm. Also, please elongate your silkscreen corners to match the style of the other QFN footprints.

Thanks!

**Comment by CarlPoirier** [comment]
Hi Ashton,

The footprint value is set to invisible. Please make it visible.

Carl

**Comment by ashtonchase** [comment]
Hi @CarlPoirier, 
Has been updated. Thanks.

**Comment by CarlPoirier** [comment]
This is great now. Thank you!

**Pull request merged**
