### PR TITLE
Added footprints for S-PVSON-N10 (special version of DFN-10-1EP-3x3mm

### PR DESCRIPTION
**Pull request by SchrodingersGat**
**Datasheet**
http://www.ti.com/lit/ds/symlink/lm5165.pdf

**Notes**
- Added version with thermal vias
- Added version without thermal vias
- Stencil is per datasheet requirements

**Examples**

_With thermal vias_
via

_Without thermal vias_
novia

_Aligned with correct 3D model_
3d

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
Silkscreen and component outlines have been fixed

**Comment by pointhi** [comment]
Fix KLC issue:

```
checking module: DFN-10-1EP_3x3mm_Pitch0.5mm_S-PVSON-N10
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
checking module: DFN-10-1EP_3x3mm_Pitch0.5mm_S-PVSON-N10_ThermalVias
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
```

**Comment by SchrodingersGat** [comment]
Clearance values have been adjusted to match datasheet spec. I think this should be acceptable for these parts.

**Comment by SchrodingersGat** [comment]
@jkriege2 please look at this - I have updated to latest KLC requirements, however these parts break a few rules:

Most importantly - custom pad values - very important to meet the spec of the footprint as per the datasheet

Also I think the courtyard offset might be playing up for non-standard shape footprints...

**Comment by jkriege2** [comment]
How does this PR compare to https://github.com/KiCad/TO_SOT_Packages_SMD.pretty/pull/32 ?

**Comment by jkriege2** [comment]
Also: Shouldn't there be a bottom-pad to counter the thermal vias?

**Comment by SchrodingersGat** [comment]
This should go in the new /Housings_SON library. I will resubmit it there.

**Pull request closed without merging**
