### PR TITLE
Lt3032

### PR DESCRIPTION
**Pull request by matyro**
Added special footprint for LT3032

I copied the existing 14 pin package and modified the exposed die pads

http://cds.linear.com/docs/en/datasheet/3032ff.pdf

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@matyro for vendor-specific footprints, the naming convention is:

**VendorName_FootprintCode**

So, in this case, it should be named `Linear_DE14MA` (and the extra dimensional information is not needed in the package name).

Additionally, please fix all the errors raised here: https://travis-ci.org/KiCad/Housings_DFN_QFN.pretty/builds/236965114

*Hint: Don't include the library name in the footprint name!*

**Comment by matyro** [comment]
> Violating Rule 10.4 
3D model name is different from footprint name (found 'DFN-14-1EP_3x4mm_Pitch0.5mm', should be 'Linear_DE14MA')

Same model should work fine

>  Violating Rule 7.4
    Second Reference Designator missing

I added ` 
(fp_text user %R (at 0 5.08) (layer F.Fab)
    (effects (font (size 1 1) (thickness 0.15)))
  )`

> Violating Rule 8.2
     - Footprint center calculated as (0.0,-0.014999999999999902)mm

Not sure about this offset, I did not change the outside boarder

**Comment by SchrodingersGat** [comment]
Thanks for the fixes. There is one further thing that I can see:
Please move the second Refdes to the middle of the footprint:

screenshot from 2017-06-01 22-27-44

(you can make it smaller if needed, in the picture I made it 0.75mm W x H)

**Comment by SchrodingersGat** [comment]
NIce work, thanks for the contributino

**Pull request merged**
