### PR TITLE
Create Microchip_8E.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
http://ww1.microchip.com/downloads/en/PackagingSpec/00000049BQ.pdf
16-Lead Plastic Quad Flat, No Lead Package (8E) - 4x4x0.9 mm Body [QFN]

big difference from generic, i would guess on a short circuit even.

### CODE REVIEW

**Comment by SchrodingersGat** [comment]
@savenlid a couple of points.

To be useful within the library, and easy to find, the naming scheme should be consistent with what's already here.

I would suggest something along the lines of:

*QFN-16-1EP_4x4mm_Pitch0.65mm_Microchip-8E.kicad_mod*

This way the name-ordering is preserved in the library, and the part remains consistent with footprint filters, etc.

I also think that the package outline on the F.Fab layer is too crowded. Please reduce just to the package outline, and reduce the size the pin-1 designator arrow.

e.g. 

qfn

**Comment by SchrodingersGat** [comment]
Hi @savenlid any interest in continuing with this PR?

**Comment by savenlid** [comment]
No

We do not speak the same language.

I do electronics for real in a professional way instead of pondering naming
schemes and sizes of pin 1 indicators.

I base my decision on technical grounds and not political.


that footprint is proven in combat, runs volume in production as we speak

case can be closed.


2017-06-08 14:49 GMT+02:00 Oliver <notifications@github.com>:

**Comment by SchrodingersGat** [comment]
Ok, great!

For reference, I have made the KLC required changes resubmitted this footprint here - https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/42

Whilst the KLC conventions might not appeal to you 100%, it is important that our library is consistent. I'm sure you can appreciate that.

Cheers :)

**Comment by savenlid** [comment]
Thanks

Yes I can appreciate some of KLC , yes.

FYI

Pin 1 marking is important  in assembly drawing / (fab layer)  its used by
assembly houses to verify correct rotation by pick and place.
It cannot be to easy to read unless it goes to absurd lengths.

Thanks again
/Nicholas


2017-06-09 3:04 GMT+02:00 Oliver <notifications@github.com>:

**Pull request closed without merging**
