### PR TITLE
fixed pin 1 indicator and splitted EPAD

### PR DESCRIPTION
**Pull request by Shackmeister**
footprints doesnt exist in provided doc
qfn36

### CODE REVIEW

**Comment by hackscribble** [comment]
Hi @Shackmeister 

For the multiple pad 37s to split up the solder paste, they need a local setting to be applied.

This is one of the other footprints in the repo (`QFN-40-1EP_6x6mm_Pitch0.5mm`) ...

image
image

For comparison, this is how the PR looks in the 3D viewer ...

image

Apart from this, I think the PR is ready to merge.

**Comment by evanshultz** [comment]
For this footprint and the one at https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/54, I think there is a better way. See the conversation at https://github.com/KiCad/LEDs.pretty/pull/39. You can have one copper pad and many smaller openings in the stencil. This is more maintainable as well.

**Comment by Shackmeister** [comment]
interesting approach, should this be the standard approach?

**Comment by evanshultz** [comment]
My understanding is yes. Oliver agreed to it and I believe it's better to maintain since if the thermal pad size changes there's only one copper element to adjust. I don't believe KLC was updated, though I mentioned it. Plus, it avoids having a plethora of "37" all over the footprint which, to me, looks better.

**Comment by Shackmeister** [comment]
@SchrodingersGat Oliver can you confirm if this should be the proper way to make splitted Epads?

**Comment by SchrodingersGat** [comment]
For multiple overlapping pads such as this, then I think this is the simplest way to do it. We should certainly settle on a best-practice and add it to the KLC

@jkriege2 @poeschlr do either of you have any input on this issue?

**Comment by evanshultz** [comment]
FYI, I proposed text for KLC to cover this at the LED PR linked above.

**Comment by Shackmeister** [comment]
@evanshultz should I made the paste layer according to the stencil design in the datasheet? (for the texas footprint)

**Comment by evanshultz** [comment]
Yes, that is the idea. Since this is a standard practice, we should do it on all footprints. If there are some unique properties of the footprint then it should be manufacturer-specific, but if the package/footprint design and thermal pad size are the same, a common stencil design is likely to yield good results for a variety of parts.

**Comment by SchrodingersGat** [comment]
@Shackmeister what is the status of this PR now?

**Comment by Shackmeister** [comment]
@SchrodingersGat Hey Oliver, welcome back :)
I've been quite busy but it should hopefully be fixed now :)

**Comment by evanshultz** [comment]
@SchrodingersGat Are you going to be able to take a look at this?

**Comment by SchrodingersGat** [comment]
Thanks for the reminder, and thanks for your work on this :)

**Pull request merged**
