### PR TITLE
Added DFN-6-1EP_3x3mm_Pitch1mm

### PR DESCRIPTION
**Pull request by Misca1234**
This is push of 3D models of the DFN-6-1EP_3x3mm_Pitch1mm

Used by this one
https://www.silabs.com/documents/public/data-sheets/Si7020-A20.pdf

kicad-library 3D model push
https://github.com/KiCad/kicad-library/pull/1659

KiCad/Housings_DFN_QFN.pretty push
https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/63

KiCad/kicad-packages3D
https://github.com/KiCad/kicad-packages3D/pull/137

easyw/kicad-3d-models-in-freecad
https://github.com/easyw/kicad-3d-models-in-freecad/pull/108

bild

bild

bild

### CODE REVIEW

**Comment by Misca1234** [comment]
Should this one have the suffix ThermalVias ?
only few in the directory have the suffix, almost all others does not

**Comment by Shackmeister** [comment]
Hey Stefan, please check out the new style for splitted Epads (see the description https://github.com/KiCad/LEDs.pretty/pull/39)

**Comment by jkriege2** [comment]
At least SI7020 does not require the version with vias ...

**Comment by Misca1234** [comment]
So what you are saying is that the epad does not need to be splitted any more ?
So I should replace the 4 epads in DFN-6-1EP_3x3mm_Pitch1mm with one ?

**Comment by Shackmeister** [comment]
You add one pad (pad 7) with the size of the Epad but with the F. Paste layer missing, then you add the 4 pads (no pinnumber!) which only on F. Paste

**Comment by Misca1234** [comment]
I will never learn or understand that pad thingy

Here it is 
bild

**Comment by Misca1234** [comment]
I guess the travis errors are ok 
(as they are in https://github.com/KiCad/LEDs.pretty/pull/39)

**Comment by SchrodingersGat** [comment]
@shackmeister any more comments on this one?

**Comment by Shackmeister** [comment]
Hey @Misca1234 
Pad 7 should have: F.cu and F.mask (F.mask is missing)
the stencil openings should only have F.Paste (there is a dropdown menu for copper, select None)

also please adjust the size of the FAB REF** so it fits inside (and change the text thickness to 15 % of the size)

**Comment by Misca1234** [comment]
bild

bild

bild

**Comment by Shackmeister** [comment]
Hi @Misca1234 
you only removed F.cu on one of the 4 pads. please fix the other
last thing to do is to reset the Solder Paste ratio clearance to 0, and instead simply set the size of the pad itself

**Comment by Misca1234** [comment]
All four "paste pads" have Solder Paste ratio clearance set to 0 and they have been increased in size to overlap each other in both X and Y directions

bild

**Comment by poeschlr** [comment]
Closing and reopening this to test our new test scripts.

**Comment by SchrodingersGat** [comment]
@Misca1234 


In preparation for the v5 KiCad software release, we are marking this repository as "legacy" and not accepting any new pull requests. These footprints have been moved to the new `kicad-footprints` repository at https://github.com/kicad/kicad-footprints

Sorry for the inconvenience, however this change will make the contribution process easier for everyone.

Please resubmit your contribution over at the new repository :)

**Pull request closed without merging**
