### PR TITLE
Added DFN-8-1EP-6x5mm_Pitch1.27mm

### PR DESCRIPTION
**Pull request by SchrodingersGat**
dfn8

Added footprint - see http://www.everspin.com/file/236/download for reference

3D model is here - https://github.com/KiCad/kicad-library/pull/442

### CODE REVIEW

**Comment by ashtonchase** [comment]
I took a look. My thoughts: 

- I understand the 10.6 KLC violation. I would be more inclined to not use default soldermask clearance values on these packages , especially considering the issues with DFN/QFN packages. Nonethless, it's not consistent with all the other footprints. 
- Please add the package outline the F.Fab layer. 
- The exposed pad for this one is smaller than typical, would you consider adding something to the name indicating that. Perhaps _small_ep or _2mm_ep

**Comment by SchrodingersGat** [comment]
So I have added the suffix _SmallFlag as per the datasheet and also added the _LargeFlag suffix. These suffixes also appear for example on Digikey for this particular package.
I have also added the package dimensions to F.Fab

**Comment by SchrodingersGat** [comment]
Outlines have been updated to conform to IPC-7351C

**Comment by pointhi** [comment]
Please fix KLC:

```
checking module: DFN-8-1EP_6x5mm_Pitch1.27mm_LargeFlag
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
checking module: DFN-8-1EP_6x5mm_Pitch1.27mm_SmallFlag
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
```

**Comment by SchrodingersGat** [comment]
Same as for other PRs. Addressing **10.6** here would invalidate the usefulness of these footprints as they have been customized for the datasheet.

And **10.7** just references other 3D models so as to not duplicate the models

**Comment by SchrodingersGat** [comment]
@jkriege2 this one has been updated to latest KLC.

It breaks two rules:

### 10.7
Properties are non-default values to conform to datasheet

### 10.8
The 3D model is the "default" one so it is not the same filename as the footprints.

**Comment by jkriege2** [comment]
Hi!

just checked this:
1. Shouldn't the 3D model be `DFN-S-8-1EP_6x5mm_Pitch1.27mm.wrl`?
2. Please fix courtyard clearance:
```
 Violating Rule 6.6
   Courtyard line has a width 0.05mm. This line is placed so that its clearance is measured from its
   center to the edges of pads and body, and its position is rounded on a grid of 0.01mm.
     A courtyard clearance in the range 0.3...0.5mm was found, but 0.25mm was expected.
     The recommendet courtyard rectangle would be:
         {'y': -2.75, 'height': 5.5, 'x': -3.7, 'width': 7.4}mm.
```

**Comment by SchrodingersGat** [comment]
Courtyard has been fixed @jkriege2

**Comment by jkriege2** [comment]
Please fix these (from new scripts)!

```
Checking footprint 'DFN-8-1EP_6x5mm_Pitch1.27mm_LargeFlag':
  Violating Rule 10.3
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
    Attribute clearance == 0.1 != 0!
    Attribute solder_mask_margin == 0.1 != 0!
    Attribute solder_paste_margin == -0.15 != 0!
  Violating Rule 10.4
    3D model reference
    Model path should start with '${KISYS3DMOD}/'
    3D model name is different from footprint name (found 'DFN-8-1EP_6x5mm_Pitch1.27mm', should be 'DFN-8-1EP_6x5mm_Pitch1.27mm_LargeFlag')

D:\KiCAD\review.pretty\kicad-library-utils\pcb>check_kicad_mod.py -vv d:\KiCAD\review.pretty\Housings_DFN_QFN.pretty\DFN-8-1EP_6x5mm_Pitch1.27mm_Small
Flag.kicad_mod
Checking footprint 'DFN-8-1EP_6x5mm_Pitch1.27mm_SmallFlag':
  Violating Rule 10.3
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
    Attribute clearance == 0.1 != 0!
    Attribute solder_mask_margin == 0.1 != 0!
    Attribute solder_paste_margin == -0.15 != 0!
  Violating Rule 10.4
    3D model reference
    Model path should start with '${KISYS3DMOD}/'
    3D model name is different from footprint name (found 'DFN-8-1EP_6x5mm_Pitch1.27mm', should be 'DFN-8-1EP_6x5mm_Pitch1.27mm_SmallFlag')
```

**Comment by SchrodingersGat** [comment]
So can 10.4 as the _Flag suffix just refers to the size of the exposed pad ( and does not change the 3D model! )

**Comment by jkriege2** [comment]
OK, but what about the `${KISYS3DMOD}/`?

**Comment by SchrodingersGat** [comment]
Done

**Pull request merged**
