### PR TITLE
Create RUM0016A.kicad_mod

### PR DESCRIPTION
**Pull request by savenlid**
existing qfn did not match the texas instrument drawing.
This one aims ti match the ti RUM0016A drawing.
Many big manufacturers have their own package drawings they refer to.
Professionals prefer to follow recommendations from individual manufacturer instead of using generic footprints if applicable,

### CODE REVIEW

**Comment by savenlid** [comment]
Updated

[RUM0016A.zip](https://github.com/KiCad/Housings_DFN_QFN.pretty/files/133829/RUM0016A.zip)

**Comment by savenlid** [comment]
[RUM0016A.zip](https://github.com/KiCad/Housings_DFN_QFN.pretty/files/139064/RUM0016A.zip)
updated

**Comment by SchrodingersGat** [comment]
Same comments as per https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/10

**Comment by SchrodingersGat** [comment]
See https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/42

**Pull request closed without merging**
