### PR TITLE
Fix all line-endings to unix

### PR DESCRIPTION
**Pull request by gauravjuvekar**
https://github.com/KiCad/kicad-library/issues/1211

### CODE REVIEW

**Comment by poeschlr** [comment]
This lib has two very large reworks of nearly all files. I think @Shackmeister should make sure that he does fix the line endings as well in his pull request https://github.com/KiCad/Housings_DFN_QFN.pretty/pull/46

**Comment by Shackmeister** [comment]
I have closed the PR since it got a bit too complicated, Ill try to split it out a bit more

**Comment by evanshultz** [comment]
This is the only PR not merged at https://github.com/KiCad/kicad-library/issues/1211. Is it possible to merge this, or are we waiting for some other tasks first?

**Comment by poeschlr** [comment]
@evanshultz I was a bit busy the last few days. (This will not change in the near future.)

Because @Shackmeister closed his pull request this one can be merged.

Thanks again @gauravjuvekar for fixing this problem.

**Pull request merged**
