### PR TITLE
Added TI S-PVQFN-40 version of the QFN-40

### PR DESCRIPTION
**Pull request by SchrodingersGat**
- Exposed pad dimensions vary from standard
- Pad size recommendations vary from standard
- Added package outline on F.Fab layer

Example component that uses this footprint:
http://www.ti.com/product/DRV8308/quality
http://www.ti.com/lit/ds/symlink/drv8308.pdf

Footprint:
qfn

3D view:
pcb

With package:
model

### CODE REVIEW

**Comment by pointhi** [comment]
please fix KLC:

```
checking module: QFN-40-1EP_6x6mm_Pitch0.5mm_TI_PVQFN-N40
  Violating Rule 10.6
    All other properties are left to default values. (Move and Place: Free; Auto Place: 0 and 0,  Local
    Clearance Values: 0)
  Violating Rule 10.7
    3D Shape ".wrl" files are named the same as their footprint and are placed in a folder named the
    same as the footprint library replacing the ".pretty" with ".3dshapes".
  Violating Rule 6.9
    Value and reference have a height of 1mm.
```

**Comment by SchrodingersGat** [comment]
I have changed the value and reference thickness to fix KLC 6.9

**10.6** - The paste values have been customized to match the datasheet
**10.7** - The 3D shapes are simply duplicated from the default version of this chip. I see no reason to duplicate the 3D file when it is exactly the same

**Comment by SchrodingersGat** [comment]
@jkriege2 updated this to match KLC also.

It violates 10.6 and 10.7 as above

**Comment by jkriege2** [comment]
Hi!

could you move crtyd a bit closer (your offset is 0.3mm, but it should be 0.25mm

Also: The DS shows thermal vias (p. 59) could you add them too?

Thanks,
JAN

**Comment by SchrodingersGat** [comment]
Hi @jkriege2 I have updated these and added a version _ThermalPad .

Please note that only the 3D model is in error as it uses the default QFN40 model

**Comment by jkriege2** [comment]
Please also add the `${KISYS3DMOD}/` to the 3D pathes

**Comment by SchrodingersGat** [comment]
Done

**Comment by jkriege2** [comment]
Hi!

also here: Nice work!

Please add bottom pad for thermal vias!

JAN

**Comment by SchrodingersGat** [comment]
Done!

**Pull request merged**
