### PR TITLE
Adding DFN-3-0.6x0.4mm

### PR DESCRIPTION
**Pull request by jeromebeguin**

### CODE REVIEW

**Comment by jkriege2** [comment]
Please provide the 3D model refernce ... the error in KLC 8.2 seems like a glitch to me ;-)

Also please provide a datasheet to check this against!

Best,
JAN

**Comment by jeromebeguin** [comment]
http://rohmfs.rohm.com/en/products/databook/datasheet/discrete/transistor/mosfet/rv3c002unt2cl-e.pdf

**Comment by jeromebeguin** [comment]
For the 3D model, I don't have it and I'm not able to add a fake file like you asked on the PR: https://github.com/KiCad/Housings_SON.pretty/pull/1, do don't know what to say about that.

**Comment by jkriege2** [comment]
Just add the correct link to a non-existent file, so the 3D model will be found, when somebody else contributes it.

Best,
JAN

**Comment by jeromebeguin** [comment]
I think there is an issue with Travis, he is saying:
Violating Rule 10.4
    3D model reference
    Model path should start with '${KISYS3DMOD}/'

But when I'm adding ${KISYS3DMOD}/ at the beginning of the path, he saying it should not be there. It's a bit confusing.

**Comment by SchrodingersGat** [comment]
Looking at the Travis logs it appears you had an extra space character at the start of the 3D model, before the ${ part...

**Comment by SchrodingersGat** [comment]
Also as this is a manufacturer specific footprint, please rename to:

`ROHM_DFN0604-3`

**Comment by SchrodingersGat** [comment]
Thanks!

Two more small things:

a) Please rotate 90deg CW so that Pin-1 is at the top-left
b) Please adjust silkscreen to indicate location of Pin-1. As this is such a small footprint, I would suggest just a small L-shaped line around the corner closest to Pin-1.

**Comment by SchrodingersGat** [comment]
Something more like this:

screenshot from 2017-05-22 23-45-40

**Comment by SchrodingersGat** [comment]
Thanks :)

**Pull request merged**
